import React,{useState,useEffect} from 'react';
import { View,Text,Switch,Linking,Share,Platform } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { api,saveSession } from './api';
import { c,s,Title,P,Label,Card,Button,Field,Chip,Avatar,ErrorNotice } from './ui';
import { SecurityPanel } from './SecurityPanel';
export function Profile({me,reload}:{me:any;reload:()=>Promise<void>}){
  const [form,setForm]=useState<any>({...me}),[options,setOptions]=useState<{genres:string[];artists:string[]}>({genres:[],artists:[]}),[instagram,setInstagram]=useState(me.instagram??''),[spotify,setSpotify]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[blocks,setBlocks]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[deleting,setDeleting]=useState(false),[password,setPassword]=useState('');
  async function extra(){const [o,sp,b,r]=await Promise.all([api.get('/v1/music/options'),api.get('/v1/integrations/spotify/status'),api.get('/v1/blocks'),api.get('/v1/reports')]);setOptions(o);setSpotify(sp);setBlocks(b.items);setReports(r.items);}
  useEffect(()=>{void extra().catch(e=>setError(e.message));},[]);
  function update(key:string,value:any){setForm((f:any)=>({...f,[key]:value}));setNotice('');}
  function toggle(key:string,value:string,limit:number){const selected=form[key].includes(value);if(!selected&&form[key].length>=limit){setError(`En fazla ${limit} seçim yapabilirsin.`);return;}update(key,selected?form[key].filter((v:string)=>v!==value):[...form[key],value]);}
  async function run(fn:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await fn();await Promise.all([reload(),extra()]);setNotice(message);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function uploadPhoto(){
    const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setError('Fotoğraf seçmek için galeri izni gerekiyor.');return;}
    const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.75,base64:true});
    if(result.canceled)return;const image=result.assets[0];if(!image.base64){setError('Fotoğraf okunamadı.');return;}
    await run(()=>api.post('/v1/profile/photos',{base64:image.base64,mimeType:image.mimeType==='image/png'?'image/png':'image/jpeg'}),'Fotoğrafın incelemeye gönderildi. Onaylandığında görünür olacak.');
  }
  async function exportData(){try{
    const data=await api.get('/v1/account/export'),json=JSON.stringify(data,null,2);
    if(Platform.OS==='web'){const blob=new Blob([json],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='ahenk-verilerim.json';link.click();URL.revokeObjectURL(url);}else await Share.share({message:json,title:'Ahenk verilerim'});
  }catch(e:any){setError(e.message);}}
  async function deleteAccount(){setBusy(true);try{await api.delete('/v1/account',{password});await saveSession(null);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  return <View style={s.section}><View><Label>SENİN SESİN</Label><Title>Biraz da senden.</Title><P muted>Ne sevdiğini, nasıl tanışmak istediğini ve neyi paylaşacağını sen seç.</P></View><ErrorNotice message={error}/>{notice&&<Card style={{backgroundColor:c.lightGreen,padding:14}}><P>{notice}</P></Card>}
    <Card style={{gap:17}}><View style={s.row}><Avatar name={me.displayName} size={65}/><View><Title small>{me.displayName}</Title><P muted>{me.email}</P></View></View><Field label="Görünen ad" value={form.displayName} onChangeText={v=>update('displayName',v)} maxLength={40}/><Field label="Kısa biyografi" value={form.bio} onChangeText={v=>update('bio',v)} multiline maxLength={280}/><Field label="Şehir" value={form.city} onChangeText={v=>update('city',v)} maxLength={60}/>
    <View style={s.row}><View style={{flex:1}}><Field label="En düşük yaş" value={String(form.ageMin)} keyboardType="number-pad" onChangeText={v=>update('ageMin',v)}/></View><View style={{flex:1}}><Field label="En yüksek yaş" value={String(form.ageMax)} keyboardType="number-pad" onChangeText={v=>update('ageMax',v)}/></View></View>
    <Label>NASIL TANIŞMAK İSTERSİN?</Label><View style={s.wrap}><Chip selected={form.intention==='friendship'} onPress={()=>update('intention','friendship')}>Arkadaşlık</Chip><Chip selected={form.intention==='dating'} onPress={()=>update('intention','dating')}>Tanışma</Chip></View>
    <Label>SEVDİĞİN TÜRLER · EN FAZLA 8</Label><View style={s.wrap}>{options.genres.map(g=><Chip key={g} selected={form.genres.includes(g)} onPress={()=>toggle('genres',g,8)}>{g}</Chip>)}</View>
    <Label>SEVDİĞİN SANATÇILAR · EN FAZLA 15</Label><View style={s.wrap}>{options.artists.map(a=><Chip key={a} selected={form.artists.includes(a)} onPress={()=>toggle('artists',a,15)}>{a}</Chip>)}</View>
    <Label>YENİ SESLERE NE KADAR AÇIKSIN?</Label><View style={s.wrap}>{[[0,'Tanıdık sesler'],[.5,'Biraz keşif'],[1,'Yeni sesler']] .map(([v,label])=><Chip key={v} selected={form.exploration===v} onPress={()=>update('exploration',v)}>{label}</Chip>)}</View>
    <View style={[s.row,{justifyContent:'space-between'}]}><P>Açık içerik etiketli parçaları göster</P><Switch accessibilityLabel="Açık içerik etiketli parçaları göster" value={form.allowExplicit} onValueChange={v=>update('allowExplicit',v)} trackColor={{true:c.green}}/></View>
    <Button busy={busy} onPress={()=>void run(()=>api.put('/v1/profile',{displayName:form.displayName,bio:form.bio,city:form.city,ageMin:Number(form.ageMin),ageMax:Number(form.ageMax),intention:form.intention,exploration:form.exploration,allowExplicit:form.allowExplicit,genres:form.genres,artists:form.artists}),'Profilin güncellendi.')}>Profili kaydet</Button>
    </Card>
    <Card style={{gap:15}}><Title small>Profil fotoğrafların</Title><P muted>Fotoğraflar inceleme tamamlandıktan sonra diğer kullanıcılara gösterilir.</P><View style={s.wrap}>{me.photos.map((p:any)=><View key={p.id} style={{gap:8,alignItems:'center',padding:8}}>{p.status!=='rejected'&&<Avatar name={me.displayName} photoId={p.id} size={72}/>}<P muted style={{fontSize:11}}>{({pending:'İnceleme bekliyor',approved:'Onaylandı',rejected:'Reddedildi'} as any)[p.status]}</P><Button small kind="light" disabled={busy} onPress={()=>void run(()=>api.delete(`/v1/profile/photos/${p.id}`),'Fotoğraf silindi.')}>Sil</Button></View>)}</View><Button kind="light" busy={busy} onPress={()=>void uploadPhoto().catch(e=>setError(e.message))}>+ Fotoğraf seç</Button></Card>
    <Card style={{gap:14}}><Title small>Instagram hesabın</Title><P muted>Kullanıcı adın profil kartında görünmez. Her eşleşmede iki tarafın ayrı ayrı paylaşım izni gerekir.</P><Field label="Instagram kullanıcı adı" value={instagram} onChangeText={setInstagram} autoCapitalize="none" placeholder="kullanici.adin" maxLength={31}/><View style={s.wrap}><Button busy={busy} onPress={()=>void run(()=>api.put('/v1/profile/instagram',{username:instagram}),'Instagram hesabın güncellendi. Önceki paylaşım izinleri sıfırlandı.')}>Kullanıcı adını kaydet</Button>{me.instagram&&<Button disabled={busy} kind="light" onPress={()=>void run(async()=>{await api.delete('/v1/profile/instagram');setInstagram('');},'Instagram hesabın kaldırıldı.')}>Hesabı kaldır</Button>}</View></Card>
    {spotify?.enabled&&<Card style={{gap:14}}><Title small>Spotify bağlantın</Title><P muted>Onayladığın ortak listeleri kendi hesabına aktar. Dinleme geçmişin bu uygulamaya alınmaz.</P>{spotify.connected?<Button kind="light" busy={busy} onPress={()=>void run(()=>api.delete('/v1/integrations/spotify'),'Bağlantı ve erişim bilgileri silindi.')}>Spotify bağlantısını kes</Button>:<Button kind="green" busy={busy} onPress={()=>void run(async()=>{const data=await api.post('/v1/integrations/spotify/connect');await Linking.openURL(data.url);},'Spotify işleminden sonra bağlantı durumunu yenile.')}>Spotify hesabını bağla</Button>}<Button kind="light" onPress={()=>void run(extra,'Bağlantı durumu güncellendi.')}>Durumu yenile</Button></Card>}
    <SecurityPanel/>
    <Card style={{gap:14}}><Title small>Gizlilik ve güvenlik</Title><Button kind="light" onPress={()=>void exportData()}>Verilerimi indir</Button><P muted style={{fontSize:12}}>Şehir düzeyinde eşleştirme yapılır. Kesin konumun istenmez. Mesajlar sunucuda şifreli saklanır; bu uçtan uca şifreleme değildir.</P>
    <Label>ENGELLEDİĞİN HESAPLAR</Label>{blocks.length?blocks.map(b=><View key={b.id} style={[s.row,{justifyContent:'space-between'}]}><P>{b.displayName}</P><Button small kind="light" disabled={busy} onPress={()=>void run(()=>api.delete(`/v1/blocks/${b.id}`),'Engel kaldırıldı. Eski sohbet ve paylaşım izinleri yeniden açılmaz.')}>Engeli kaldır</Button></View>):<P muted>Engellenen hesap yok.</P>}
    <Label>ŞİKÂYETLERİN</Label>{reports.length?reports.map(r=><P key={r.id} muted style={{fontSize:12}}>{new Date(r.created_at).toLocaleDateString('tr-TR')} · {r.status==='open'?'İnceleniyor':'Sonuçlandırıldı'}</P>):<P muted>Gönderilmiş şikâyet yok.</P>}
    <Button kind="danger" onPress={()=>setDeleting(!deleting)}>Hesabımı sil</Button>{deleting&&<View style={{gap:12}}><P>Hesabın, sohbetlerin, eşleşmelerin ve bağlantı bilgilerin silinir. Bu işlem geri alınamaz.</P><Field label="Silme işlemi için parolan" secureTextEntry value={password} onChangeText={setPassword}/><Button kind="danger" busy={busy} disabled={!password} onPress={()=>void deleteAccount()}>Hesabımı ve verilerimi kalıcı olarak sil</Button><Button kind="light" onPress={()=>setDeleting(false)}>Vazgeç</Button></View>}
    </Card>
  </View>;
}